name: Run RSpec Tests
on: [push, pull_request]

env:
  RUBY_VERSION: 2.3.5
  MYSQL_DATABASE_HOST: localhost
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: r00tp@ss
  MYSQL_DATABASE: mysms_test

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-16.04

    services:
        mysql:
          image: mysql:5.7
          ports:
            - 3306

    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install MySQL client package 
        run: sudo apt-get install libmysqlclient-dev       
      - name: Install dependencies
        run: |
          gem install bundler -v 1.17
          bundler install
      - name: Initialize database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rspec        
